name: Foundation.MSSQLHelper

on:
  push:
    branches: [main]

jobs:
  BuildAndPack:
    runs-on: ubuntu-latest
    steps:
      - name: "Git: Checkout main with full history"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Install dotnet 6.0"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Insert GitHub package token
        run: sed -i 's/{github_access_token}/${{secrets.NUGET_API_KEY}}/' NuGet.config

      - name: "pack and push"
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          API_SOURCE: https://nuget.pkg.github.com/MCCITGIT/index.json
          NUGET_VERSION: 0.0.1
        run: |
          dotnet build -c Release ./src/MCC.Foundation.MSSQLHelper.sln
          dotnet pack ./src/MCC.Foundation.MSSQLHelper.csproj -p:PackageVersion=$NUGET_VERSION -o .
          dotnet nuget push **/*$NUGET_VERSION*.nupkg -k $API_KEY -s $API_SOURCE --skip-duplicate
